development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # Changed url
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: redis://redistogo:6341dc769ceb1f3d4f62ca925d22e049@crestfish.redistogo.com:11283/
  channel_prefix: chat-rails-redux_production
